# Generated by Django 3.2.8 on 2021-11-05 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('press', '0003_auto_20211104_1840'),
    ]

    operations = [
        migrations.AddField(
            model_name='cooluser',
            name='gh_following',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
